### ISSUE TITLE
VS 2015 Support

### ISSUE THREAD

**Issue by eamodio** [paulcbetts/SaveAllTheTime#38]
Please :)

**Comment by paulcbetts** [comment]
I can't even build the project anymore, because it's built against VS2012 and it's impossible to install the VS2012 Addin SDK on VS2013. You could try manually editing the VSIX to "support" VS2015

**Comment by eamodio** [comment]
Do you care about keeping 2012 support? If I got it working in 2013/2015 would you accept it?

**Comment by paulcbetts** [comment]
I'd love that, yeah

**Comment by eamodio** [comment]
Looks like @hmemcpy beat me too it! :)
